In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [4]:
df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\titanic\train.csv', usecols=['Age', 'Pclass', 'SibSp', 'Parch', 'Survived'])

In [5]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [7]:
df.dropna(inplace=True)

In [11]:
x = df.iloc[:,1:5]
y = df['Survived']

In [12]:
np.mean(cross_val_score(LogisticRegression(),x,y, scoring='accuracy', cv=20))

np.float64(0.6933333333333332)

# Feature Construction

In [15]:
x['Family_Size'] = x['SibSp']+ x['Parch'] + 1

In [16]:
x.head()

   Pclass   Age  SibSp  Parch  Family_Size
0       3  22.0      1      0            2
1       1  38.0      1      0            2
2       3  26.0      0      0            1
3       1  35.0      1      0            2
4       3  35.0      0      0            1

In [17]:
def myFn(num):
    if num == 0:
        # alone
        return 0
    elif num == 1:
        # small family
        return 1
    else :
        # large family
        return 2

In [18]:
myFn(4)

2

Applying fn on dataset

In [21]:
x['Family_Type'] = x['Family_Size'].apply(myFn)

In [25]:
x.drop(columns=['SibSp','Parch','Family_Size'], inplace=True)

In [26]:
x.head()

   Pclass   Age  Family_Type
0       3  22.0            2
1       1  38.0            2
2       3  26.0            1
3       1  35.0            2
4       3  35.0            1

In [27]:
np.mean(cross_val_score(LogisticRegression(),x,y, scoring='accuracy', cv=20))

np.float64(0.7172619047619048)

# Feature Splitting

In [28]:
df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\titanic\train.csv')

In [33]:
# Here name col contains surName,Salutn,name
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [34]:
# extracting comas vals
df['Name'].str.split(',', expand=True)

             0                                            1
0       Braund                              Mr. Owen Harris
1      Cumings   Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                  Miss. Laina
3     Futrelle           Mrs. Jacques Heath (Lily May Peel)
4        Allen                            Mr. William Henry
..         ...                                          ...
886   Montvila                                  Rev. Juozas
887     Graham                         Miss. Margaret Edith
888   Johnston               Miss. Catherine Helen "Carrie"
889       Behr                              Mr. Karl Howell
890     Dooley                                  Mr. Patrick

[891 rows x 2 columns]

In [35]:
# We want salutatn, so idx will be 1
df['Name'].str.split(',', expand=True)[1]

0                                  Mr. Owen Harris
1       Mrs. John Bradley (Florence Briggs Thayer)
2                                      Miss. Laina
3               Mrs. Jacques Heath (Lily May Peel)
4                                Mr. William Henry
                          ...
886                                    Rev. Juozas
887                           Miss. Margaret Edith
888                 Miss. Catherine Helen "Carrie"
889                                Mr. Karl Howell
890                                    Mr. Patrick
Name: 1, Length: 891, dtype: object

In [37]:
# Now we want val present before '.' which is at idx 0
df['Name'].str.split(',', expand=True)[1].str.split('.', expand=True)[0]

0         Mr
1        Mrs
2       Miss
3        Mrs
4         Mr
       ...
886      Rev
887     Miss
888     Miss
889       Mr
890       Mr
Name: 0, Length: 891, dtype: object

In [45]:
# Now taking salutatn into new col
df['Title'] = df['Name'].str.split(',', expand=True)[1].str.split('.', expand=True)[0]

In [39]:
df[['Title','Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [65]:
# Analysing a/c to this
# (df.groupby('Title').mean()['Survived']).sort_values(ascending=False)

In [49]:
df['Is_Married'] = 0
df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

C:\Users\HP\AppData\Local\Temp\ipykernel_8552\2254989826.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Is_Married'].loc[df['Title'] == 'Mrs'] = 1

In [64]:
df['Is_Married'].sample(5)

519    0
18     0
220    0
342    0
183    0
Name: Is_Married, dtype: int64