# Softmax Regression

A form of Logistic Regression which deals with more than two class data or Multinomial Logistic Reg

- LR is a specializatn of Softmax with 2 classes

> Softmax Fn

It calculate the probability of individual classes
<img src='img30.png'></img>

> Training Intuition
1. First transform third class(OHE)
2. Form 3 dataset with individual(OHE transformed) class
3. Treat them as 3 new model and find their coef which will be 3 for each
4. Then finding z val and then their prob

Conclusion -
- You are training Logistic Regression models equal to classes numbers and finding equal no of coef for each model
- Then finding z val for each model
- And then convert that z val into Probability using softmax fn and model with max prob, assign by pt

> Problem with this intuition
- Due to finding coef individually for each model, it makes process very slow
- And this intuition is not used by scikit learn
- SOLN : Scikit finds all of 9 coef with single model

> Implementatn

In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
enc = LabelEncoder()
df['species'] = enc.fit_transform(df['species'])

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [6]:
df = df[['sepal_length','petal_length','species']]

In [7]:
df.head()

   sepal_length  petal_length  species
0           5.1           1.4        0
1           4.9           1.4        0
2           4.7           1.3        0
3           4.6           1.5        0
4           5.0           1.4        0

In [8]:
x = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [9]:
x_tr, x_ts, y_tr, y_ts = train_test_split(x,y, test_size=0.2, random_state=2)

In [ ]:
clf = LogisticRegression(multi_class='multinomial')

TypeError: LogisticRegression.__init__() got an unexpected keyword argument 'multi_class'

In [ ]:
clf.fit(x_tr,y_tr)

In [ ]:
y_pred = clf.predict(x_ts)

In [ ]:
print(accuracy_score(y_ts,y_pred))

In [ ]:
pd.DataFrame(confusion_matrix(y_ts, y_pred))

In [ ]:
# predictn
query = np.array([3,4,2,7])
clf.predict_proba(query)

In [ ]:
clf.predict(query)

In [ ]:
from mlxtend.plotting import plot_decision_regions

plot_decision_regions(x.values, y.values, clf, legend=2)

# Adding axes annotatn
plt.xlabel('sepal_length [cm]')
plt.ylabel('petal length [cm]')
plt.title('Softmax on Iris')

plt.show()

# Poynomial Logistic Regression

- We can apply logisitc reg on non linear data by using polynomial features using degrees transformatn