In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\orders.csv')
time = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\pyCourse\csvFiles\messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

- when we import dataframe, it's date & time values are stored as objects(strings)
- So we need to change it into date & time

In [5]:
date['date'] = pd.to_datetime(date['date'])

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

Extracting year, month & month_name, date

In [8]:
date['year'] = date['date'].dt.year
date['month'] = date['date'].dt.month
date['month_name'] = date['date'].dt.month_name()
date['day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  year  month month_name  day
0 2019-12-10        5628       25       3  2019     12   December   10
1 2018-08-15        3646       14     157  2018      8     August   15
2 2018-10-23        1859       25       1  2018     10    October   23
3 2019-08-17        7292       25       1  2019      8     August   17
4 2019-01-06        4344       25       3  2019      1    January    6

In [10]:
# days of week
date['dow'] = date['date'].dt.day_of_week
# day of week name
date['dow_name'] = date['date'].dt.day_name()
# is weekend
date['date_is_weekend'] = np.where(date['dow_name'].isin(['Sunday','Monday']),1,0)
# week of year
date['date_week'] = date['date'].dt.weekday
# semester of year
date['semester'] = np.where(date['date'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,year,month,month_name,day,dow,dow_name,date_is_weekend,date_week,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,1,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,2,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,1,2
3,2019-08-17,2019,8,August,17,5,Saturday,0,5,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,6,2

In [11]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 2, 20, 18, 50, 18, 881454)

In [12]:
(today - date['date']).dt.days

0      2264
1      2746
2      2677
3      2379
4      2602
       ...
995    2692
996    2633
997    2481
998    2546
999    2320
Name: date, Length: 1000, dtype: int64

In [14]:
# month passed 
np.round((today - date['date']) / np.timedelta64(1,'W'),0)

0      324.0
1      392.0
2      383.0
3      340.0
4      372.0
       ...
995    385.0
996    376.0
997    355.0
998    364.0
999    332.0
Name: date, Length: 1000, dtype: float64

# Extrating time

In [15]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [16]:
time['date'] = pd.to_datetime(time['date'])

In [17]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

Extracting hours, mins, secnds

In [21]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [19]:
# extracting time part 
time['time'] = time['date'].dt.time

In [20]:
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00